name: Nextflow CI

on:
  pull_request:
    branches:
      - development
      - master

jobs:
  test_sarscov2_user:
    name: Run pipeline test (sarscov2_user)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (sarscov2_user)
        run: |
          nextflow run main.nf -profile docker --prefix "covidmvp-user-$(date +%Y-%m-%d)" -params-file covidmvp_user_params.yaml

  test_sarscov2_reference:
    name: Run pipeline test (sarscov2_reference)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (sarscov2_reference)
        run: |
          nextflow run main.nf -profile docker --prefix "covidmvp-clinical-$(date +%Y-%m-%d)" --end_date $(date +%Y-%m-%d) -params-file covidmvp_clinical_params.yaml

  test_sarscov2_timeseries:
    name: Run pipeline test (sarscov2_timeseries)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (sarscov2_timeseries)
        run: |
          nextflow run main.nf -profile docker --prefix "covidmvp-timeseries-$(date +%Y-%m-%d)" -params-file covidmvp_timeseries_params.yaml

  test_sarscov2_wastewater:
    name: Run pipeline test (sarscov2_wastewater)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (sarscov2_wastewater)
        run: |
          nextflow run main.nf -profile docker --prefix "covidmvp-wastewater-$(date +%Y-%m-%d)" -params-file covidmvp_wastewater_params.yaml

  test_mpox_user:
    name: Run pipeline test (mpox_user)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (mpox_user)
        run: |
          nextflow run main.nf -profile docker --prefix "poxmvp-user-$(date +%Y-%m-%d)" -params-file poxmvp_user_params.yaml

  test_mpox_reference:
    name: Run pipeline test (mpox_reference)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline test (mpox_reference)
        run: |
          nextflow run main.nf -profile docker --prefix "poxmvp-reference-$(date +%Y-%m-%d)" -params-file poxmvp_clinical_params.yaml

  check_success:
    name: Check if all tests passed
    needs:
      [
        test_sarscov2_user,
        test_sarscov2_reference,
        test_sarscov2_timeseries,
        test_sarscov2_wastewater,
        test_mpox_reference,
        test_mpox_user
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        if: ${{ failure() }}
        run: exit 1
